server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:  # 注意这里也是写在spring旗下的,不可另起,只能写这
    config:
      server:
        git:
          uri: https://github.com/KyleSun96/config-test.git  #github放配置文件仓库的克隆url

eureka:
  instance:
    hostname: localhost # 主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信